[package]
name = "hopper-fuzz"
version = "0.1.0"
authors = ["Brian L. Troutwine <brian@troutwine.us>"]

[dependencies]
hopper = { git = "https://github.com/postmates/hopper.git", branch = "telemetry_et_al" }
tempdir = "0.3"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9.2"
